### ISSUE TITLE
setup: wrong platform detection in docker

### ISSUE THREAD

**Issue by a1eaiactaest** [wafflephi/lib#8]
Running `docker build - < dockerfile` in [`VAMPA/data collector/`](https://github.com/wafflephi/VAMPA/blob/6c52e5d225adffc0c9b0880d8dc97ef1b4720851/data%20collector/dockerfile#L12) results in this error:
```
[...]
 => ERROR [4/4] RUN pip install git+https://github.com/wafflephi/lib.git                                      2.4s 
------                                                                                                             
 > [4/4] RUN pip install git+https://github.com/wafflephi/lib.git:                                                 
#7 0.381 Collecting git+https://github.com/wafflephi/lib.git                                                       
#7 0.381   Cloning https://github.com/wafflephi/lib.git to /tmp/pip-req-build-b5ub2cyn                             
#7 0.384   Running command git clone --filter=blob:none --quiet https://github.com/wafflephi/lib.git /tmp/pip-req-build-b5ub2cyn                                                                                                      
#7 1.909   Resolved https://github.com/wafflephi/lib.git to commit f5699683a303dac9274eeb6fb30195abd2541d90
#7 1.917   Preparing metadata (setup.py): started
#7 2.185   Preparing metadata (setup.py): finished with status 'error'
#7 2.208   error: subprocess-exited-with-error
#7 2.208   
#7 2.208   × python setup.py egg_info did not run successfully.
#7 2.208   │ exit code: 1
#7 2.208   ╰─> [7 lines of output]
#7 2.208       Traceback (most recent call last):
#7 2.208         File "<string>", line 2, in <module>
#7 2.208         File "<pip-setuptools-caller>", line 34, in <module>
#7 2.208         File "/tmp/pip-req-build-b5ub2cyn/setup.py", line 38, in <module>
#7 2.208           TENSORFLOW_VERSION,
#7 2.208           ^^^^^^^^^^^^^^^^^^
#7 2.208       NameError: name 'TENSORFLOW_VERSION' is not defined
#7 2.208       [end of output]
#7 2.208   
#7 2.208   note: This error originates from a subprocess, and is likely not a problem with pip.
#7 2.209 error: metadata-generation-failed
#7 2.209 
#7 2.209 × Encountered error while generating package metadata.
#7 2.209 ╰─> See above for output.
#7 2.209 
#7 2.209 note: This is an issue with the package mentioned above, not pip.
#7 2.209 hint: See above for details.
------
executor failed running [/bin/sh -c pip install git+https://github.com/wafflephi/lib.git]: exit code: 1
```

Reason for that might be wrong platform detection resulting in wrong or none Tensorflow version. As stated in https://github.com/wafflephi/lib/blob/f5699683a303dac9274eeb6fb30195abd2541d90/setup.py#L13
there is no basecase for `TENSORFLOW_VERSION` variable.

**Comment by a1eaiactaest** [comment]
Changed basecase `TENSORFLOW_VERSION` to `tensorflow` which should be exact version used in docker.
```
#7 5.999 ERROR: No matching distribution found for tensorflow
```
Also found this: https://github.com/docker/for-mac/issues/5320

**Comment by a1eaiactaest** [comment]
One of the possible solutions is to remove Tensorflow package from requirements as sugested in [this SO thread](https://stackoverflow.com/questions/52521190/error-installing-tensorflow-in-docker-image). This will result in user-side errors but if user has installed Tensorflow independetly everything should work.

**Comment by a1eaiactaest** [comment]
Pending review from @NullBy1e

**Comment by a1eaiactaest** [comment]
> Changed basecase `TENSORFLOW_VERSION` to `tensorflow` which should be exact version used in docker.
> 
> ```
> #7 5.999 ERROR: No matching distribution found for tensorflow
> ```
> 
> Also found this: [docker/for-mac#5320](https://github.com/docker/for-mac/issues/5320)

I should mention this was run with the line in `dockerfile` changed as follows:
```
diff --git a/data collector/dockerfile b/data collector/dockerfile
index 80b065f..8188f02 100644
--- a/data collector/dockerfile 
+++ b/data collector/dockerfile 
@@ -9,8 +9,6 @@ RUN pip install --no-cache-dir --upgrade pip && \
        pip install --no-cache-dir numpy pandas requests
 
 #* Install wafflephi lib
-RUN pip install git+https://github.com/wafflephi/lib.git
+RUN pip install git+https://github.com/a1eaiactaest/lib.git
 ```
And using this fork: [a1eaiactaest/lib](https://github.com/a1eaiactaest/lib)

**Comment by NullBy1e** [comment]
Your fork seems to solve the problem on my Intel Mac but I had to downgrade the Python version to 3.10.10, because latest TensorFlow doesn't run on anything above 3.10.
@a1eaiactaest Can you check if you can install TensorFlow with the 3.10.10 version of the Python docker image?

**Comment by a1eaiactaest** [comment]
@NullBy1e is this right?
```
prybiec@m1chine:~/Projects/wafflephi/VAMPA/data collector$ pip3 --version
pip 22.3.1 from /opt/homebrew/lib/python3.10/site-packages/pip (python 3.10)
prybiec@m1chine:~/Projects/wafflephi/VAMPA/data collector$ python3 --version
Python 3.10.9
prybiec@m1chine:~/Projects/wafflephi/VAMPA/data collector$ python3 -m pip freeze | grep tensorflow
WARNING: Could not find a Python project for directory /opt/homebrew/lib/python3.10/site-packages/utils-0.0.0-py3.10.egg (tried all parent directories)
tensorflow-estimator==2.10.0
tensorflow-macos==2.10.0
```

**Comment by NullBy1e** [comment]
> @NullBy1e is this right?
> 
> ```
> prybiec@m1chine:~/Projects/wafflephi/VAMPA/data collector$ pip3 --version
> pip 22.3.1 from /opt/homebrew/lib/python3.10/site-packages/pip (python 3.10)
> prybiec@m1chine:~/Projects/wafflephi/VAMPA/data collector$ python3 --version
> Python 3.10.9
> prybiec@m1chine:~/Projects/wafflephi/VAMPA/data collector$ python3 -m pip freeze | grep tensorflow
> WARNING: Could not find a Python project for directory /opt/homebrew/lib/python3.10/site-packages/utils-0.0.0-py3.10.egg (tried all parent directories)
> tensorflow-estimator==2.10.0
> tensorflow-macos==2.10.0
> ```
@a1eaiactaest if I read this correctly it should be in the dockerfile itself and not your direct terminal python environment.
Check my edit on the comment above for the first line to be updated in your dockerfile.
